In [2]:
import numpy as np
import pprint

In [5]:
np_array = np.arange(1, 11, 1)
print(np_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
np_array = np.linspace(1, 10, 6)
print(np_array)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [16]:
np_array = (np.zeros((3, 6)))  # row , column
print(np_array)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
print(np_array.shape)

(3, 6)


In [18]:
np_array = np_array.reshape(6, 3)
print(np_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np_array)
print(np_array.ravel())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [24]:
print(np_array.min())
print(np_array.max())

1
9


In [29]:
print(np_array)
print(np_array.sum(axis=0))  # column wise sum
print(np_array.sum(axis=1))  # row wise sum

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [30]:
print(np.std(np_array))  # standard deviation

2.581988897471611


In [4]:
a = np.zeros((2, 2))
print(a)
b = np.ones((2, 2))
print(b)
print(a + b + 2)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]]


In [5]:
print(a.dot(b)) # dot product


[[0. 0.]
 [0. 0.]]


.flat iterates over each element in np_array regardless of its dimension and prints each element

In [8]:
for cell in np_array.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [12]:
print(a)
print(b)
print(np.vstack((a, b)))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [13]:
print(a)
print(b)
print(np.hstack((a, b)))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]
